# Generated by Django 4.2.16 on 2024-10-25 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0002_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='signatures',
            field=models.ManyToManyField(blank=True, related_name='signed_petitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='signature',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_entries', to='complaints.petition'),
        ),
        migrations.AlterUniqueTogether(
            name='signature',
            unique_together={('user', 'petition')},
        ),
    ]
