# Generated by Django 4.2.16 on 2024-10-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_petition_signatures_petition_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
