# Generated by Django 4.2.16 on 2024-10-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_petition_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='petitions/'),
        ),
    ]
