# Generated by Django 4.2.16 on 2024-10-29 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.petition'),
        ),
    ]
